Fix reference to `Base.path_separator`
```julia
julia> Base.path_separator
ERROR: UndefVarError: `path_separator` not defined in `Base`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base_compiler.jl:47
 [2] top-level scope
   @ REPL[5]:1

julia> Base.Filesystem.path_separator
"/"

julia> VERSION
v"1.12.6"
```